create extension if not exists "pg_cron" with schema "pg_catalog";

create type "public"."conversation_role" as enum ('user', 'assistant', 'system');

create type "public"."shoping_cart_status" as enum ('active', 'completed');

drop trigger if exists "fanatic_games_insert_embedding" on "public"."fanatic_games";

alter table "public"."fanatic_answers" drop constraint "fanatic_answers_user_id_fkey";

drop function if exists "public"."fanatic_get_current_riddles"();


  create table "public"."coin_earnings_log" (
    "id" bigint generated by default as identity not null,
    "profile_id" uuid,
    "description" text,
    "earned_coins" integer,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."coin_earnings_log" enable row level security;


  create table "public"."product_catalog" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "description" text,
    "stock" integer,
    "is_active" boolean,
    "image_url" text,
    "product_embedding" extensions.vector,
    "product_details" jsonb
      );


alter table "public"."product_catalog" enable row level security;


  create table "public"."product_pricing" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint,
    "price" double precision,
    "discount" double precision,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."product_pricing" enable row level security;


  create table "public"."shopping_cart_items" (
    "id" bigint generated by default as identity not null,
    "cart_id" bigint,
    "priced_product_id" bigint
      );


alter table "public"."shopping_cart_items" enable row level security;


  create table "public"."shopping_carts" (
    "id" bigint generated by default as identity not null,
    "profile_id" uuid,
    "cart_status" public.shoping_cart_status
      );


alter table "public"."shopping_carts" enable row level security;


  create table "public"."thunder_conversations" (
    "id" bigint generated by default as identity not null,
    "profile_id" uuid,
    "content" text,
    "role" public.conversation_role,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."thunder_conversations" enable row level security;

alter table "public"."fanatic_answers" drop column "user_id";

alter table "public"."fanatic_answers" add column "profile_id" uuid;

alter table "public"."profiles" add column "avatar_url" text;

CREATE UNIQUE INDEX coin_earnings_log_pkey ON public.coin_earnings_log USING btree (id);

CREATE UNIQUE INDEX product_catalog_pkey ON public.product_catalog USING btree (id);

CREATE UNIQUE INDEX product_pricing_pkey ON public.product_pricing USING btree (id);

CREATE UNIQUE INDEX shopping_cart_items_pkey ON public.shopping_cart_items USING btree (id);

CREATE UNIQUE INDEX shopping_carts_pkey ON public.shopping_carts USING btree (id);

CREATE UNIQUE INDEX thunder_conversations_pkey ON public.thunder_conversations USING btree (id);

alter table "public"."coin_earnings_log" add constraint "coin_earnings_log_pkey" PRIMARY KEY using index "coin_earnings_log_pkey";

alter table "public"."product_catalog" add constraint "product_catalog_pkey" PRIMARY KEY using index "product_catalog_pkey";

alter table "public"."product_pricing" add constraint "product_pricing_pkey" PRIMARY KEY using index "product_pricing_pkey";

alter table "public"."shopping_cart_items" add constraint "shopping_cart_items_pkey" PRIMARY KEY using index "shopping_cart_items_pkey";

alter table "public"."shopping_carts" add constraint "shopping_carts_pkey" PRIMARY KEY using index "shopping_carts_pkey";

alter table "public"."thunder_conversations" add constraint "thunder_conversations_pkey" PRIMARY KEY using index "thunder_conversations_pkey";

alter table "public"."coin_earnings_log" add constraint "coin_earnings_log_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."coin_earnings_log" validate constraint "coin_earnings_log_profile_id_fkey";

alter table "public"."fanatic_answers" add constraint "fanatic_answers_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."fanatic_answers" validate constraint "fanatic_answers_profile_id_fkey";

alter table "public"."product_pricing" add constraint "product_pricing_discount_check" CHECK (((discount >= (0)::double precision) AND (discount < (1)::double precision))) not valid;

alter table "public"."product_pricing" validate constraint "product_pricing_discount_check";

alter table "public"."product_pricing" add constraint "product_pricing_price_check" CHECK ((price > (0)::double precision)) not valid;

alter table "public"."product_pricing" validate constraint "product_pricing_price_check";

alter table "public"."product_pricing" add constraint "product_pricing_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.product_catalog(id) not valid;

alter table "public"."product_pricing" validate constraint "product_pricing_product_id_fkey";

alter table "public"."shopping_cart_items" add constraint "shopping_cart_items_cart_id_fkey" FOREIGN KEY (cart_id) REFERENCES public.shopping_carts(id) not valid;

alter table "public"."shopping_cart_items" validate constraint "shopping_cart_items_cart_id_fkey";

alter table "public"."shopping_cart_items" add constraint "shopping_cart_items_priced_product_id_fkey" FOREIGN KEY (priced_product_id) REFERENCES public.product_pricing(id) not valid;

alter table "public"."shopping_cart_items" validate constraint "shopping_cart_items_priced_product_id_fkey";

alter table "public"."shopping_carts" add constraint "shopping_carts_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."shopping_carts" validate constraint "shopping_carts_profile_id_fkey";

alter table "public"."thunder_conversations" add constraint "thunder_conversations_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."thunder_conversations" validate constraint "thunder_conversations_profile_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.fanatic_best_try(pprofileid uuid)
 RETURNS TABLE(best_score numeric, highest_similarity numeric)
 LANGUAGE sql
AS $function$
SELECT 
  max(awarded_points) AS most_points,
  max(similarity_score) AS best_similarity
FROM fanatic_answers 
WHERE 
  game_id = (select active_game_id from fanatic_active_game_id()) and 
  profile_id = pProfileId;
$function$
;

CREATE OR REPLACE FUNCTION public.fanatic_next_riddle_date()
 RETURNS timestamp with time zone
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  vStartDate          TIMESTAMPTZ;
  vDaysElapsed        INT;
  vDaysBetweenRiddles INT;
  vTotalRiddles       INT;
  vCurrentRiddleIndex INT;
BEGIN
  SELECT start_date, DATE_PART('day', NOW() - start_date)::INT
  INTO vStartDate, vDaysElapsed
  FROM fanatic_games
  WHERE NOW() BETWEEN start_date AND end_date;

  -- No active game
  IF vStartDate IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT value::INT
  INTO vDaysBetweenRiddles
  FROM fanatic_game_config
  WHERE key = 'days_between_riddles';

  SELECT COUNT(*)
  INTO vTotalRiddles
  FROM fanatic_riddles fr
  JOIN fanatic_games fg ON fg.id = fr.game_id
  WHERE NOW() BETWEEN fg.start_date AND fg.end_date;

  vCurrentRiddleIndex := vDaysElapsed / vDaysBetweenRiddles;

  -- Game has run out of riddles
  IF vCurrentRiddleIndex >= vTotalRiddles THEN
    RETURN NULL;
  END IF;

  RETURN vStartDate + ((vCurrentRiddleIndex + 1) * vDaysBetweenRiddles) * INTERVAL '1 day';
END;
$function$
;

CREATE OR REPLACE FUNCTION public.fanatic_remaining_game_tries(pprofileid uuid)
 RETURNS TABLE(remaining_tries_game integer, remaining_tries_today integer, next_attempt_date timestamp with time zone)
 LANGUAGE plpgsql
AS $function$DECLARE
  vTriesPerUserPerGame INT;
  vTriesPerUserPerDay  INT;
  vActiveGameId        INT;
  vRemainingGameTries  INT;
  vRemainingTriesToday INT;
  vNextAttemptDate     TIMESTAMPTZ;
  vOldestWindowAnswer  TIMESTAMPTZ;
BEGIN

  SELECT active_game_id
  INTO vActiveGameId
  FROM fanatic_active_game_id();

  IF vActiveGameId IS NULL THEN
    RAISE EXCEPTION 'No active games.';
  END IF;

  -- Load play limits from config
  SELECT value::int INTO vTriesPerUserPerGame
  FROM fanatic_game_config WHERE key = 'tries_per_user_per_game';

  SELECT value::int INTO vTriesPerUserPerDay
  FROM fanatic_game_config WHERE key = 'tries_per_user_per_day';

  -- Remaining tries for the game
  SELECT GREATEST(vTriesPerUserPerGame - COUNT(*), 0)
  INTO vRemainingGameTries
  FROM fanatic_answers
  WHERE profile_id = pProfileId
    AND game_id = vActiveGameId;

  -- Remaining tries within the 24-hour rolling window
  SELECT GREATEST(vTriesPerUserPerDay - COUNT(*), 0)
  INTO vRemainingTriesToday
  FROM fanatic_answers
  WHERE profile_id = pProfileId
    AND game_id = vActiveGameId
    AND created_at >= NOW() - INTERVAL '24 hours';

  -- Determine when the user can play next
  IF vRemainingGameTries = 0 THEN
    -- User has exhausted all tries for this game, no further attempts allowed
    vRemainingTriesToday := 0;
    vNextAttemptDate     := NULL;

  ELSIF vRemainingTriesToday = 0 THEN
    -- Daily window exhausted. Find the oldest answer in the current 24h window.
    -- The next slot opens exactly 24h after that oldest answer falls out of the window.
    SELECT MIN(created_at)
    INTO vOldestWindowAnswer
    FROM (
      SELECT created_at
      FROM fanatic_answers
      WHERE profile_id = pProfileId
        AND game_id = vActiveGameId
        AND created_at >= NOW() - INTERVAL '24 hours'
      ORDER BY created_at ASC
      LIMIT vTriesPerUserPerDay          -- only consider the tries that filled the quota
    ) sub;

    vNextAttemptDate := vOldestWindowAnswer + INTERVAL '24 hours';

  ELSE
    -- User still has tries available, can play immediately
    vNextAttemptDate := NULL;

  END IF;

  RETURN QUERY SELECT vRemainingGameTries, vRemainingTriesToday, vNextAttemptDate;
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_top_products(query_embedding extensions.vector, top_n integer)
 RETURNS TABLE(id integer, name character varying, description text, stock integer, is_active boolean, image_url text, product_details jsonb, price numeric, discount numeric)
 LANGUAGE sql
AS $function$
    SELECT 
    p.id,
    p.name,
    p.description,
    p.stock,
    p.is_active,
    p.image_url,
    p.product_details,
    latest_price.price,
    latest_price.discount
FROM product_catalog p
JOIN (
    -- Get only the most recent price per product
    SELECT DISTINCT ON (product_id)
        product_id,
        price,
        discount
    FROM product_pricing
    ORDER BY product_id, created_at DESC
) AS latest_price ON p.id = latest_price.product_id
WHERE p.is_active = true
ORDER BY p.product_embedding <=> query_embedding
LIMIT top_n;
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_create_profile()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  INSERT INTO profiles 
    (profile_id, username) 
    VALUES (NEW.user_id, 'user_' || substr(md5(NEW.user_id::text), 1, 8));
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_delete_expired_conversations()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    DELETE FROM thunder_conversations
    WHERE id IN (
        SELECT id
        FROM thunder_conversations
        WHERE profile_id = NEW.profile_id
        ORDER BY created_at
        OFFSET 50
    );

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_generate_fanatic_embedding()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  PERFORM net.http_post(
    url := 'https://upktcnvztyldwzapbuqq.supabase.co/functions/v1/question-embedding-generator'::text,
    body := jsonb_build_object(
      'record', jsonb_build_object(
        'id', NEW.id,
        'answer', NEW.answer
      )
    ),
    headers := '{"Content-Type": "application/json"}'::jsonb
  );

  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_generate_product_embedding()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  PERFORM net.http_post(
    url := 'https://upktcnvztyldwzapbuqq.supabase.co/functions/v1/product-embedding-generator'::text,
    body := jsonb_build_object(
      'record', jsonb_build_object(
        'id', NEW.id,
        'product', jsonb_build_object(
          'name', NEW.name,
          'description', NEW.description,
          'details', NEW.product_details
        )::text
      )
    ),
    headers := '{"Content-Type": "application/json"}'::jsonb
  );

  RETURN NEW;
END;
$function$
;

grant delete on table "public"."coin_earnings_log" to "anon";

grant insert on table "public"."coin_earnings_log" to "anon";

grant references on table "public"."coin_earnings_log" to "anon";

grant select on table "public"."coin_earnings_log" to "anon";

grant trigger on table "public"."coin_earnings_log" to "anon";

grant truncate on table "public"."coin_earnings_log" to "anon";

grant update on table "public"."coin_earnings_log" to "anon";

grant delete on table "public"."coin_earnings_log" to "authenticated";

grant insert on table "public"."coin_earnings_log" to "authenticated";

grant references on table "public"."coin_earnings_log" to "authenticated";

grant select on table "public"."coin_earnings_log" to "authenticated";

grant trigger on table "public"."coin_earnings_log" to "authenticated";

grant truncate on table "public"."coin_earnings_log" to "authenticated";

grant update on table "public"."coin_earnings_log" to "authenticated";

grant delete on table "public"."coin_earnings_log" to "service_role";

grant insert on table "public"."coin_earnings_log" to "service_role";

grant references on table "public"."coin_earnings_log" to "service_role";

grant select on table "public"."coin_earnings_log" to "service_role";

grant trigger on table "public"."coin_earnings_log" to "service_role";

grant truncate on table "public"."coin_earnings_log" to "service_role";

grant update on table "public"."coin_earnings_log" to "service_role";

grant delete on table "public"."product_catalog" to "anon";

grant insert on table "public"."product_catalog" to "anon";

grant references on table "public"."product_catalog" to "anon";

grant select on table "public"."product_catalog" to "anon";

grant trigger on table "public"."product_catalog" to "anon";

grant truncate on table "public"."product_catalog" to "anon";

grant update on table "public"."product_catalog" to "anon";

grant delete on table "public"."product_catalog" to "authenticated";

grant insert on table "public"."product_catalog" to "authenticated";

grant references on table "public"."product_catalog" to "authenticated";

grant select on table "public"."product_catalog" to "authenticated";

grant trigger on table "public"."product_catalog" to "authenticated";

grant truncate on table "public"."product_catalog" to "authenticated";

grant update on table "public"."product_catalog" to "authenticated";

grant delete on table "public"."product_catalog" to "service_role";

grant insert on table "public"."product_catalog" to "service_role";

grant references on table "public"."product_catalog" to "service_role";

grant select on table "public"."product_catalog" to "service_role";

grant trigger on table "public"."product_catalog" to "service_role";

grant truncate on table "public"."product_catalog" to "service_role";

grant update on table "public"."product_catalog" to "service_role";

grant delete on table "public"."product_pricing" to "anon";

grant insert on table "public"."product_pricing" to "anon";

grant references on table "public"."product_pricing" to "anon";

grant select on table "public"."product_pricing" to "anon";

grant trigger on table "public"."product_pricing" to "anon";

grant truncate on table "public"."product_pricing" to "anon";

grant update on table "public"."product_pricing" to "anon";

grant delete on table "public"."product_pricing" to "authenticated";

grant insert on table "public"."product_pricing" to "authenticated";

grant references on table "public"."product_pricing" to "authenticated";

grant select on table "public"."product_pricing" to "authenticated";

grant trigger on table "public"."product_pricing" to "authenticated";

grant truncate on table "public"."product_pricing" to "authenticated";

grant update on table "public"."product_pricing" to "authenticated";

grant delete on table "public"."product_pricing" to "service_role";

grant insert on table "public"."product_pricing" to "service_role";

grant references on table "public"."product_pricing" to "service_role";

grant select on table "public"."product_pricing" to "service_role";

grant trigger on table "public"."product_pricing" to "service_role";

grant truncate on table "public"."product_pricing" to "service_role";

grant update on table "public"."product_pricing" to "service_role";

grant delete on table "public"."shopping_cart_items" to "anon";

grant insert on table "public"."shopping_cart_items" to "anon";

grant references on table "public"."shopping_cart_items" to "anon";

grant select on table "public"."shopping_cart_items" to "anon";

grant trigger on table "public"."shopping_cart_items" to "anon";

grant truncate on table "public"."shopping_cart_items" to "anon";

grant update on table "public"."shopping_cart_items" to "anon";

grant delete on table "public"."shopping_cart_items" to "authenticated";

grant insert on table "public"."shopping_cart_items" to "authenticated";

grant references on table "public"."shopping_cart_items" to "authenticated";

grant select on table "public"."shopping_cart_items" to "authenticated";

grant trigger on table "public"."shopping_cart_items" to "authenticated";

grant truncate on table "public"."shopping_cart_items" to "authenticated";

grant update on table "public"."shopping_cart_items" to "authenticated";

grant delete on table "public"."shopping_cart_items" to "service_role";

grant insert on table "public"."shopping_cart_items" to "service_role";

grant references on table "public"."shopping_cart_items" to "service_role";

grant select on table "public"."shopping_cart_items" to "service_role";

grant trigger on table "public"."shopping_cart_items" to "service_role";

grant truncate on table "public"."shopping_cart_items" to "service_role";

grant update on table "public"."shopping_cart_items" to "service_role";

grant delete on table "public"."shopping_carts" to "anon";

grant insert on table "public"."shopping_carts" to "anon";

grant references on table "public"."shopping_carts" to "anon";

grant select on table "public"."shopping_carts" to "anon";

grant trigger on table "public"."shopping_carts" to "anon";

grant truncate on table "public"."shopping_carts" to "anon";

grant update on table "public"."shopping_carts" to "anon";

grant delete on table "public"."shopping_carts" to "authenticated";

grant insert on table "public"."shopping_carts" to "authenticated";

grant references on table "public"."shopping_carts" to "authenticated";

grant select on table "public"."shopping_carts" to "authenticated";

grant trigger on table "public"."shopping_carts" to "authenticated";

grant truncate on table "public"."shopping_carts" to "authenticated";

grant update on table "public"."shopping_carts" to "authenticated";

grant delete on table "public"."shopping_carts" to "service_role";

grant insert on table "public"."shopping_carts" to "service_role";

grant references on table "public"."shopping_carts" to "service_role";

grant select on table "public"."shopping_carts" to "service_role";

grant trigger on table "public"."shopping_carts" to "service_role";

grant truncate on table "public"."shopping_carts" to "service_role";

grant update on table "public"."shopping_carts" to "service_role";

grant delete on table "public"."thunder_conversations" to "anon";

grant insert on table "public"."thunder_conversations" to "anon";

grant references on table "public"."thunder_conversations" to "anon";

grant select on table "public"."thunder_conversations" to "anon";

grant trigger on table "public"."thunder_conversations" to "anon";

grant truncate on table "public"."thunder_conversations" to "anon";

grant update on table "public"."thunder_conversations" to "anon";

grant delete on table "public"."thunder_conversations" to "authenticated";

grant insert on table "public"."thunder_conversations" to "authenticated";

grant references on table "public"."thunder_conversations" to "authenticated";

grant select on table "public"."thunder_conversations" to "authenticated";

grant trigger on table "public"."thunder_conversations" to "authenticated";

grant truncate on table "public"."thunder_conversations" to "authenticated";

grant update on table "public"."thunder_conversations" to "authenticated";

grant delete on table "public"."thunder_conversations" to "service_role";

grant insert on table "public"."thunder_conversations" to "service_role";

grant references on table "public"."thunder_conversations" to "service_role";

grant select on table "public"."thunder_conversations" to "service_role";

grant trigger on table "public"."thunder_conversations" to "service_role";

grant truncate on table "public"."thunder_conversations" to "service_role";

grant update on table "public"."thunder_conversations" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."fanatic_answers"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable users to view their own data only"
  on "public"."fanatic_answers"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = profile_id));



  create policy "Enable read access for all users"
  on "public"."fanatic_game_config"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."fanatic_games"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."fanatic_riddles"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."product_catalog"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."product_pricing"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."shopping_cart_items"
  as permissive
  for select
  to public
using (true);



  create policy "Enable users to view their own data only"
  on "public"."shopping_carts"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = profile_id));



  create policy "Enable insert for users based on user_id"
  on "public"."thunder_conversations"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = profile_id));



  create policy "Enable users to view their own data only"
  on "public"."thunder_conversations"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = profile_id));


CREATE TRIGGER on_fanatic_answer_change AFTER INSERT OR UPDATE OF answer ON public.fanatic_games FOR EACH ROW EXECUTE FUNCTION public.trigger_generate_fanatic_embedding();

CREATE TRIGGER on_product_change AFTER INSERT OR UPDATE OF name, description, product_details ON public.product_catalog FOR EACH ROW EXECUTE FUNCTION public.trigger_generate_product_embedding();

CREATE TRIGGER trg_delete_expired_conversations AFTER INSERT ON public.thunder_conversations FOR EACH ROW EXECUTE FUNCTION public.trigger_delete_expired_conversations();

CREATE TRIGGER trg_create_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.trigger_create_profile();


