


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";






CREATE TYPE "public"."fanatic_game_categories" AS ENUM (
    'who',
    'where',
    'what'
);


ALTER TYPE "public"."fanatic_game_categories" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."fanatic_active_game_id"() RETURNS TABLE("active_game_id" integer)
    LANGUAGE "sql"
    AS $$
SELECT 
  id
  FROM fanatic_games 
  WHERE NOW() BETWEEN start_date AND end_date
$$;


ALTER FUNCTION "public"."fanatic_active_game_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."fanatic_days_elapsed"() RETURNS TABLE("days_elapsed" integer)
    LANGUAGE "sql"
    AS $$
SELECT 
  DATE_PART('day', NOW() - start_date) AS days_elapsed
FROM fanatic_games 
WHERE NOW() BETWEEN start_date AND end_date
$$;


ALTER FUNCTION "public"."fanatic_days_elapsed"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."fanatic_get_current_game"() RETURNS TABLE("game_category" "public"."fanatic_game_categories", "sort_order" integer, "riddle" "text")
    LANGUAGE "sql"
    AS $$
WITH current_game AS (
    SELECT 
        id AS current_game_id,
        game_category,
        DATE_PART('day', NOW() - start_date) AS days_elapsed
    FROM fanatic_games 
    WHERE NOW() BETWEEN start_date AND end_date
),
config AS (
    SELECT value::int AS days_per_riddle
    FROM fanatic_game_config 
    WHERE key = 'days_between_riddles'
),
riddle_number AS (
    SELECT 
        (days_elapsed / days_per_riddle) AS current_riddle
    FROM current_game, config
)
SELECT 
    game_category,
    sort_order, 
    riddle
FROM fanatic_riddles, current_game, riddle_number
WHERE game_id = current_game_id 
AND sort_order <= current_riddle;
$$;


ALTER FUNCTION "public"."fanatic_get_current_game"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."fanatic_get_current_riddles"() RETURNS TABLE("game_category" "public"."fanatic_game_categories", "sort_order" integer, "riddle" "text")
    LANGUAGE "sql"
    AS $$
WITH current_game AS (
    SELECT 
        id AS current_game_id,
        game_category,
        DATE_PART('day', NOW() - start_date) AS days_elapsed
    FROM fanatic_games 
    WHERE NOW() BETWEEN start_date AND end_date
),
config AS (
    SELECT value::int AS days_per_riddle
    FROM fanatic_game_config 
    WHERE key = 'days_between_riddles'
),
riddle_number AS (
    SELECT 
        (days_elapsed / days_per_riddle) + 1 AS current_riddle
    FROM current_game, config
)
SELECT 
game_category,
    sort_order, 
    riddle
FROM fanatic_riddles, current_game, riddle_number
WHERE game_id = current_game_id 
AND sort_order <= current_riddle;
$$;


ALTER FUNCTION "public"."fanatic_get_current_riddles"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."fanatic_answers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "answer" "text",
    "game_id" bigint,
    "awarded_points" bigint,
    "similarity_score" double precision,
    "is_correct" boolean,
    "user_id" "uuid"
);


ALTER TABLE "public"."fanatic_answers" OWNER TO "postgres";


COMMENT ON COLUMN "public"."fanatic_answers"."game_id" IS 'the game which the riddle is linked to';



COMMENT ON COLUMN "public"."fanatic_answers"."similarity_score" IS 'how similar was the answer to the correct one';



COMMENT ON COLUMN "public"."fanatic_answers"."is_correct" IS 'was the answers similarity higher than the minimum threashold defined in the game config table.';



ALTER TABLE "public"."fanatic_answers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fanatic_answers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."fanatic_game_config" (
    "key" "text" NOT NULL,
    "value" "text" NOT NULL,
    "description" "text"
);


ALTER TABLE "public"."fanatic_game_config" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."fanatic_games" (
    "id" bigint NOT NULL,
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "answer" "text" NOT NULL,
    "answer_embedding" "extensions"."vector"(1024),
    "game_category" "public"."fanatic_game_categories"
);


ALTER TABLE "public"."fanatic_games" OWNER TO "postgres";


ALTER TABLE "public"."fanatic_games" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fanatic_games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."fanatic_riddles" (
    "id" bigint NOT NULL,
    "game_id" bigint,
    "riddle" "text",
    "sort_order" smallint
);


ALTER TABLE "public"."fanatic_riddles" OWNER TO "postgres";


ALTER TABLE "public"."fanatic_riddles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fanatic_riddles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "username" character varying NOT NULL,
    "fanatic_coins" bigint DEFAULT '0'::bigint NOT NULL,
    "id" "uuid" NOT NULL
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


COMMENT ON COLUMN "public"."profiles"."fanatic_coins" IS 'coins earned from playing the fanatic minigame';



ALTER TABLE ONLY "public"."fanatic_answers"
    ADD CONSTRAINT "fanatic_answers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fanatic_game_config"
    ADD CONSTRAINT "fanatic_game_config_pkey" PRIMARY KEY ("key");



ALTER TABLE ONLY "public"."fanatic_games"
    ADD CONSTRAINT "fanatic_games_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fanatic_riddles"
    ADD CONSTRAINT "fanatic_riddles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fanatic_riddles"
    ADD CONSTRAINT "unique_game_riddle_order" UNIQUE ("game_id", "sort_order");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_username_key" UNIQUE ("username");





ALTER TABLE ONLY "public"."fanatic_answers"
    ADD CONSTRAINT "fanatic_answers_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."fanatic_games"("id");



ALTER TABLE ONLY "public"."fanatic_answers"
    ADD CONSTRAINT "fanatic_answers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."fanatic_riddles"
    ADD CONSTRAINT "fanatic_riddles_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."fanatic_games"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE "public"."fanatic_answers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fanatic_game_config" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fanatic_games" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fanatic_riddles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";















































































































































































































































































































































































































































































































GRANT ALL ON FUNCTION "public"."fanatic_active_game_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."fanatic_active_game_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."fanatic_active_game_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."fanatic_days_elapsed"() TO "anon";
GRANT ALL ON FUNCTION "public"."fanatic_days_elapsed"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."fanatic_days_elapsed"() TO "service_role";



GRANT ALL ON FUNCTION "public"."fanatic_get_current_game"() TO "anon";
GRANT ALL ON FUNCTION "public"."fanatic_get_current_game"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."fanatic_get_current_game"() TO "service_role";



GRANT ALL ON FUNCTION "public"."fanatic_get_current_riddles"() TO "anon";
GRANT ALL ON FUNCTION "public"."fanatic_get_current_riddles"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."fanatic_get_current_riddles"() TO "service_role";






























GRANT ALL ON TABLE "public"."fanatic_answers" TO "anon";
GRANT ALL ON TABLE "public"."fanatic_answers" TO "authenticated";
GRANT ALL ON TABLE "public"."fanatic_answers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fanatic_answers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."fanatic_answers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fanatic_answers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fanatic_game_config" TO "anon";
GRANT ALL ON TABLE "public"."fanatic_game_config" TO "authenticated";
GRANT ALL ON TABLE "public"."fanatic_game_config" TO "service_role";



GRANT ALL ON TABLE "public"."fanatic_games" TO "anon";
GRANT ALL ON TABLE "public"."fanatic_games" TO "authenticated";
GRANT ALL ON TABLE "public"."fanatic_games" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fanatic_games_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."fanatic_games_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fanatic_games_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fanatic_riddles" TO "anon";
GRANT ALL ON TABLE "public"."fanatic_riddles" TO "authenticated";
GRANT ALL ON TABLE "public"."fanatic_riddles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fanatic_riddles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."fanatic_riddles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fanatic_riddles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































