drop trigger if exists "on_fanatic_answer_change" on "public"."fanatic_games";

drop trigger if exists "trg_schedule_fanatic_end_date" on "public"."fanatic_games";

drop trigger if exists "on_product_change" on "public"."product_catalog";

drop trigger if exists "trg_delete_expired_conversations" on "public"."thunder_conversations";

alter table "public"."coin_earnings_log" drop constraint "coin_earnings_log_profile_id_fkey";

alter table "public"."fanatic_answers" drop constraint "fanatic_answers_game_id_fkey";

alter table "public"."fanatic_answers" drop constraint "fanatic_answers_profile_id_fkey";

alter table "public"."fanatic_riddles" drop constraint "fanatic_riddles_game_id_fkey";

alter table "public"."product_pricing" drop constraint "product_pricing_product_id_fkey";

alter table "public"."shopping_cart_items" drop constraint "shopping_cart_items_cart_id_fkey";

alter table "public"."shopping_cart_items" drop constraint "shopping_cart_items_priced_product_id_fkey";

alter table "public"."shopping_carts" drop constraint "shopping_carts_profile_id_fkey";

alter table "public"."thunder_conversations" drop constraint "thunder_conversations_profile_id_fkey";

drop function if exists "public"."get_top_products"(query_embedding vector, top_n integer);

drop function if exists "public"."fanatic_get_current_game"();


  create table "public"."notifications" (
    "id" bigint generated by default as identity not null,
    "profile_id" uuid,
    "title" character varying not null,
    "body" text,
    "read" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."notifications" enable row level security;

alter table "public"."fanatic_games" alter column "answer_embedding" set data type extensions.vector(1024) using "answer_embedding"::extensions.vector(1024);

alter table "public"."fanatic_games" alter column "game_category" set data type public.fanatic_game_categories using "game_category"::text::public.fanatic_game_categories;

alter table "public"."product_catalog" alter column "product_embedding" set data type extensions.vector using "product_embedding"::extensions.vector;

alter table "public"."shopping_carts" alter column "cart_status" set data type public.shoping_cart_status using "cart_status"::text::public.shoping_cart_status;

alter table "public"."thunder_conversations" alter column "role" set data type public.conversation_role using "role"::text::public.conversation_role;

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."notifications" add constraint "notifications_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."notifications" validate constraint "notifications_profile_id_fkey";

alter table "public"."coin_earnings_log" add constraint "coin_earnings_log_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."coin_earnings_log" validate constraint "coin_earnings_log_profile_id_fkey";

alter table "public"."fanatic_answers" add constraint "fanatic_answers_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public.fanatic_games(id) not valid;

alter table "public"."fanatic_answers" validate constraint "fanatic_answers_game_id_fkey";

alter table "public"."fanatic_answers" add constraint "fanatic_answers_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."fanatic_answers" validate constraint "fanatic_answers_profile_id_fkey";

alter table "public"."fanatic_riddles" add constraint "fanatic_riddles_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public.fanatic_games(id) not valid;

alter table "public"."fanatic_riddles" validate constraint "fanatic_riddles_game_id_fkey";

alter table "public"."product_pricing" add constraint "product_pricing_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.product_catalog(id) not valid;

alter table "public"."product_pricing" validate constraint "product_pricing_product_id_fkey";

alter table "public"."shopping_cart_items" add constraint "shopping_cart_items_cart_id_fkey" FOREIGN KEY (cart_id) REFERENCES public.shopping_carts(id) not valid;

alter table "public"."shopping_cart_items" validate constraint "shopping_cart_items_cart_id_fkey";

alter table "public"."shopping_cart_items" add constraint "shopping_cart_items_priced_product_id_fkey" FOREIGN KEY (priced_product_id) REFERENCES public.product_pricing(id) not valid;

alter table "public"."shopping_cart_items" validate constraint "shopping_cart_items_priced_product_id_fkey";

alter table "public"."shopping_carts" add constraint "shopping_carts_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."shopping_carts" validate constraint "shopping_carts_profile_id_fkey";

alter table "public"."thunder_conversations" add constraint "thunder_conversations_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) not valid;

alter table "public"."thunder_conversations" validate constraint "thunder_conversations_profile_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_top_products(query_embedding extensions.vector, top_n integer)
 RETURNS TABLE(id integer, name character varying, description text, stock integer, is_active boolean, image_url text, product_details jsonb, price numeric, discount numeric)
 LANGUAGE sql
AS $function$
    SELECT 
    p.id,
    p.name,
    p.description,
    p.stock,
    p.is_active,
    p.image_url,
    p.product_details,
    latest_price.price,
    latest_price.discount
FROM product_catalog p
JOIN (
    -- Get only the most recent price per product
    SELECT DISTINCT ON (product_id)
        product_id,
        price,
        discount
    FROM product_pricing
    ORDER BY product_id, created_at DESC
) AS latest_price ON p.id = latest_price.product_id
WHERE p.is_active = true
ORDER BY p.product_embedding <=> query_embedding
LIMIT top_n;
$function$
;

CREATE OR REPLACE PROCEDURE public.assign_fanatic_coins(IN p_game_id integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $procedure$
DECLARE
  v_profile_id UUID;
  v_answer_id INT;
  v_awarded_points INT;
BEGIN

  FOR v_profile_id, v_answer_id, v_awarded_points IN
    SELECT profile_id, answer_id, max_points
    FROM fanatic_game_results
    WHERE game_id = p_game_id
  LOOP
    UPDATE profiles 
    SET fanatic_coins = fanatic_coins + v_awarded_points
    WHERE id = v_profile_id;

    INSERT INTO coin_earnings_log 
      (profile_id, description, earned_coins)
    VALUES
      (
        v_profile_id,
        'Earned in fanatic game. game_id:  ' || p_game_id,
        v_awarded_points
      );

    INSERT INTO notifications
    (profile_id, title, body)
    VALUES
    (
      v_profile_id, 'Fanatic game scored!', 
      'The results from the last Fanatic game have been scored. You earned ' || 
        TO_CHAR(v_awarded_points, 'FM999,999,999') || 
        ' coins. Congrats!'
    );
  END LOOP;
END;
$procedure$
;

create or replace view "public"."fanatic_game_results" as  SELECT DISTINCT ON (profile_id) game_id,
    profile_id,
    id AS answer_id,
    awarded_points AS max_points
   FROM public.fanatic_answers
  WHERE (game_id = 1)
  ORDER BY profile_id, awarded_points DESC;


CREATE OR REPLACE FUNCTION public.fanatic_get_current_game()
 RETURNS TABLE(game_category public.fanatic_game_categories, sort_order integer, riddle text)
 LANGUAGE sql
AS $function$
WITH current_game AS (
    SELECT 
        id AS current_game_id,
        game_category,
        DATE_PART('day', NOW() - start_date) AS days_elapsed
    FROM fanatic_games 
    WHERE NOW() BETWEEN start_date AND end_date
),
config AS (
    SELECT value::int AS days_per_riddle
    FROM fanatic_game_config 
    WHERE key = 'days_between_riddles'
),
riddle_number AS (
    SELECT 
        (days_elapsed / days_per_riddle) AS current_riddle
    FROM current_game, config
)
SELECT 
    game_category,
    sort_order, 
    riddle
FROM fanatic_riddles, current_game, riddle_number
WHERE game_id = current_game_id 
AND sort_order <= current_riddle;
$function$
;

CREATE OR REPLACE FUNCTION public.trigger_fanatic_cron()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_job_name TEXT;
  v_cron_expr TEXT;
BEGIN
  -- Handle DELETE: remove the cronjob
  IF TG_OP = 'DELETE' THEN
    v_job_name := 'end_date_job_' || OLD.id;
    BEGIN
      PERFORM cron.unschedule(v_job_name);
    EXCEPTION WHEN others THEN
      NULL;
    END;
    RETURN OLD;
  END IF;

  -- Handle UPDATE: remove the old cronjob before rescheduling
  IF TG_OP = 'UPDATE' THEN
    v_job_name := 'end_date_job_' || OLD.id;
    BEGIN
      PERFORM cron.unschedule(v_job_name);
    EXCEPTION WHEN others THEN
      NULL;
    END;
  END IF;

  -- Handle INSERT and UPDATE: schedule the cronjob
  v_job_name := 'end_date_job_' || NEW.id;
  v_cron_expr := to_char(NEW.end_date, 'MI HH24 DD MM') || ' *';

  PERFORM cron.schedule(
    v_job_name,
    v_cron_expr,
    format(
      $sql$
        CALL assign_fanatic_coins(%L);
        SELECT cron.unschedule(%L);
      $sql$,
      NEW.id,
      v_job_name
    )
  );

  RETURN NEW;
END;
$function$
;

grant delete on table "public"."notifications" to "anon";

grant insert on table "public"."notifications" to "anon";

grant references on table "public"."notifications" to "anon";

grant select on table "public"."notifications" to "anon";

grant trigger on table "public"."notifications" to "anon";

grant truncate on table "public"."notifications" to "anon";

grant update on table "public"."notifications" to "anon";

grant delete on table "public"."notifications" to "authenticated";

grant insert on table "public"."notifications" to "authenticated";

grant references on table "public"."notifications" to "authenticated";

grant select on table "public"."notifications" to "authenticated";

grant trigger on table "public"."notifications" to "authenticated";

grant truncate on table "public"."notifications" to "authenticated";

grant update on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";


  create policy "Enable users to view their own data only"
  on "public"."notifications"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = profile_id));


CREATE TRIGGER on_fanatic_answer_change AFTER INSERT OR UPDATE OF answer ON public.fanatic_games FOR EACH ROW EXECUTE FUNCTION public.trigger_generate_fanatic_embedding();

CREATE TRIGGER trg_schedule_fanatic_end_date AFTER INSERT OR DELETE OR UPDATE OF end_date ON public.fanatic_games FOR EACH ROW EXECUTE FUNCTION public.trigger_fanatic_cron();

CREATE TRIGGER on_product_change AFTER INSERT OR UPDATE OF name, description, product_details ON public.product_catalog FOR EACH ROW EXECUTE FUNCTION public.trigger_generate_product_embedding();

CREATE TRIGGER trg_delete_expired_conversations AFTER INSERT ON public.thunder_conversations FOR EACH ROW EXECUTE FUNCTION public.trigger_delete_expired_conversations();

drop trigger if exists "trg_create_profile" on "auth"."users";

CREATE TRIGGER trg_create_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.trigger_create_profile();


